artifacts_root: artifacts 

data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Tushar040903/Datasets/blob/main/Food_Time_Data_Set.zip?raw=true
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation: 
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion/Food_Time_Data_Set.csv
  STATUS_FILE: artifacts/data_validation/status.txt

  
data_transformation:
  root_dir: artifacts/data_transformation
  input_file: artifacts/data_ingestion/Food_Time_Data_Set.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts\data_transformation\train.csv
  test_data_path: artifacts\data_transformation\test.csv
  model_name: model.joblib
  

model_evaluation:
  root_dir: artifacts/model_evalution
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metrics_file: artifacts/model_evalution/metrics.json
