artifacts_root: artifacts 

data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Tushar040903/Datasets/blob/main/food_delivery.zip?raw=true
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion